import React, { useState, useEffect } from "react";
import { Loader, Card, FormField } from "../components/index.js";
import axios from "axios";
import "../App.css";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  const [isModalOpen, setIsModalOpen] = useState(true);

  const closeModal = () => {
    setIsModalOpen(false);
  };

  useEffect(() => {
    const fetchPost = async () => {
      setLoading(true);
      try {

        const res = await axios.get("http://localhost:3000/api/v1/post");
        setAllPosts(res.data.data);

      } catch (error) {
        alert(error);
      } finally {
        setLoading(false);
      }
    };
    fetchPost();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        //debounce
        const searchResults = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );

        setSearchResults(searchResults);
      }, 500)
    );
  };

  return (
    <div >
      {isModalOpen  && (
        <div className="modal" onClick={closeModal}>
          <div className="py-20 border-black border-2 bg-white relative" style={{width:"700px"}} >
            <div className="flex justify-end ">
              <span
                className=" absolute top-0 right-2 cursor-pointer flex 
              justify-center items-center text-red-500 text-xlg scale-150 font-bold"
                onClick={closeModal}
              >
                &times;
              </span>
            </div>
            <div className="flex justify-center items-center">
              <p className="font-bold text-red-500 text-center text-2xl">
                "Priyanshu07804" Pay credits $ for AI Image Generation, please
                use Only Once.
              </p>
            </div>
          </div>
        </div>
      )}

      <section className="max-w-7x1 mx-auto">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            the Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse Through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
        </div>
        <div className="mt-16">
          <FormField
            LabelName="search Posts"
            type="text"
            name="text"
            placeholder="searchPosts"
            value={searchText}
            handleChange={handleSearchChange}
          />
        </div>
        <div className="mt-10">
          {loading ? (
            <div className="flex justify-center items-center">
              <Loader />
            </div>
          ) : (
            <>
              {searchText && (
                <h2 className="font-medium text-[#666e75] text-xl mb-3">
                  Showing results for{" "}
                  <span className="text-[#222328]">{searchText}</span>
                </h2>
              )}
              <div className="grid lg-grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {searchText ? (
                  <RenderCards
                    data={searchResults}
                    title="No search results found"
                  />
                ) : (
                  <RenderCards data={allPosts} title="no posts found" />
                )}
              </div>
            </>
          )}
        </div>
      </section>
    </div>
  );
};

export default Home;
